services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: movie_rec_postgres
    restart: always
    environment:
      POSTGRES_USER: rec_user
      POSTGRES_PASSWORD: rec_password
      POSTGRES_DB: movie_rec_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rec_user -d movie_rec_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
